Add option to explicitly delegate FQDN's
cunnie/sslip.io pull request #27
Opened 2023-04-27 12:29 UTC by TimeToogo

Following on from #24 I ended up implementing a workaround for this issue that exposes a new argument which can be used to delegate FQDN's to other nameservers. This has enabled me to successfully issue wildcard letsencrypt certificates on the sslip domain. Here's how I use it:

```
sslip.io-dns-server -delegate _acme-challenge.sslip.example.domain=ns-XXX.awsdns-XX.com.
```

Where Route53 has a hosted zone for `sslip.example.domain` and will answer authoritatively for  `_acme-challenge.sslip.example.domain`, which enables certbot to pass the acme dns-01 challenge. You could likely substitute Route53 for other nameservers using this approach although I haven't tested any others.
I'm not sure if this is something you want to bring into the mainline but thought it was worth checking.

**NOTE:** I learnt the hard way that the dns01 challenge issues mixed case queries, hence the case-insensitive match.

2023-05-02 13:57 UTC, cunnie commented
Thanks for the contribution, @TimeToogo. It might take me a while to get to this PR, but I'm intrigued by your idea.

2023-07-10 10:45 UTC, cunnie commented
Hi @TimeToogo , thanks in advance for the PR. Here are some changes I'd like to see:

- **Squash your commits**. I'd like to see one self-contained commit, not three, especially when one of the commit is a fix on an earlier commit (i.e. "fix binding")
- **Commit message should describe the "why"**. Your commit messages describe the "what" (e.g. "Add option to explicitly delegate FQDN's") but the "what" isn't as important as the "why". What problem are we trying to fix? For inspiration, look at some of the commit messages in the Linux kernel. Here's an [example](https://github.com/torvalds/linux/commit/fdb54d96600aafe45951f549866cd6fc1af59954). Note: I appreciate how hard it is to write a good commit message—it takes effort to be clear and concise.
- Use **consistent argument parsing** (see comment in code).
- **Write tests**. Here's the [file](https://github.com/cunnie/sslip.io/blob/7f73d65d762939fe28bbccc8ecb56fbe87f13617/src/sslip.io-dns-server/integration_flags_test.go) you want to write your tests in. Pattern it after the `-addresses` tests.
- **Documentation**: [this](https://github.com/cunnie/sslip.io/blob/main/docs/wildcard.md) page needs to be updated to describe how to use your feature to procure a wildcard certificate.

Thanks for putting the time to make sslip.io better. —Brian

2023-11-29 22:03 UTC, cunnie requested changes

2025-06-17 14:11 UTC, alanthian approved these changes

2025-06-17 14:11 UTC, alanthian approved these changes

2025-06-17 19:43 UTC, cunnie commented
Hi @TimeToogo @alanthian 

Thanks for your interest in sslip.io!  This project is primarily a personal
"for fun" project and I'm not actively looking to grow a community or accept
contributions at this time.

If you have an idea for an improvement:

- Forking is encouraged! Please feel free to fork the repository and make the
changes you'd like to see. You can then use your own forked version.
- If you're feeling particularly ambitious, deploy servers running your forked
code. A diverse ecosystem is better. Period.

I'm generally not accepting pull requests for the following reasons:

- Maintaining my vision: I have a specific vision for how sslip.io works and
evolves.
- Time commitment: Reviewing and merging pull requests takes time and focus
that I prefer to spend elsewhere.
- Keeping it simple: I want to keep the project manageable and avoid feature
creep.

However, I might consider pull requests for the following:

- Critical security vulnerabilities: If you discover a serious security flaw,
please report it responsibly by opening an issue.
- Bugs: Include tests, use good commit messages, and squash your commits.
- Minor documentation fixes: Typos or small clarifications in the documentation
are welcome.

Thanks for understanding!

2025-06-17 19:43 UTC, closed without merging

2025-06-18 00:09 UTC, alanthian reviewed
ok

2025-06-19 03:11 UTC, alanthian reviewed
ok